# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeid', models.PositiveIntegerField(default=0)),
                ('module', models.PositiveSmallIntegerField(default=0)),
                ('test', models.BooleanField(default=0)),
                ('truth', models.BooleanField(default=0)),
            ],
        ),
    ]
