# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.PositiveIntegerField(default=0)),
                ('test', models.BooleanField(default=0)),
                ('truth', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(default=0)),
                ('test', models.BooleanField(default=0)),
                ('truth', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveIntegerField(default=0)),
                ('test', models.BooleanField(default=0)),
                ('truth', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.PositiveIntegerField(default=0)),
                ('test', models.BooleanField(default=0)),
                ('truth', models.BooleanField(default=0)),
            ],
        ),
    ]
