# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0003_modulea_modulep_moduler_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaesarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caesarid', models.PositiveIntegerField(default=0)),
                ('cardnum', models.PositiveIntegerField(default=0)),
                ('dmxind01', models.CharField(max_length=20)),
                ('dmx10bytestring01', models.CharField(max_length=20)),
                ('dmx2bytestring02', models.CharField(max_length=20)),
                ('rqotrantimealt', models.CharField(max_length=20)),
                ('tcaclientamt', models.CharField(max_length=50)),
                ('rua20bytestring001', models.CharField(max_length=50)),
                ('ruaind004', models.CharField(max_length=20)),
                ('dmxind03', models.CharField(max_length=20)),
                ('sign', models.CharField(max_length=20)),
            ],
        ),
    ]
