# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0004_caesardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caesardata',
            name='caesarid',
            field=models.CharField(max_length=30),
        ),
    ]
