# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0008_auto_20180819_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caesardata',
            name='cardnum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='dmx10bytestring01',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='dmx2bytestring02',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='dmxind01',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='dmxind03',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='rqotrantimealt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='rua20bytestring001',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='ruaind004',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='sign',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caesardata',
            name='tcaclientamt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
