# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0009_auto_20180819_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeid', models.PositiveIntegerField(default=0)),
                ('test', models.PositiveSmallIntegerField(default=0)),
                ('truth', models.PositiveSmallIntegerField(default=0)),
                ('module', models.PositiveSmallIntegerField(default=0)),
                ('p', models.PositiveSmallIntegerField(default=0)),
                ('r', models.PositiveSmallIntegerField(default=0)),
                ('s', models.PositiveSmallIntegerField(default=0)),
                ('a', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
