# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0011_auto_20180822_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='disturb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='recall',
            field=models.FloatField(default=0),
        ),
    ]
