# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0012_auto_20180822_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='ModuleA',
        ),
        migrations.DeleteModel(
            name='ModuleP',
        ),
        migrations.DeleteModel(
            name='ModuleR',
        ),
        migrations.DeleteModel(
            name='ModuleS',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
