# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_caesar', '0013_auto_20180823_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='module0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module15',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module16',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module17',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module18',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='module9',
            field=models.FloatField(default=0),
        ),
    ]
