# -*- coding: utf-8 -*-

from django.db import models


class Trade(models.Model):
    tradeid = models.PositiveIntegerField(default=0)
    test = models.PositiveSmallIntegerField(default=0)
    truth = models.PositiveSmallIntegerField(default=0)
    module = models.PositiveSmallIntegerField(default=0)
    p = models.SmallIntegerField(default=0)
    r = models.SmallIntegerField(default=0)
    s = models.SmallIntegerField(default=0)
    a = models.SmallIntegerField(default=0)
    accuracy = models.FloatField(default=0)
    precision = models.FloatField(default=0)
    recall = models.FloatField(default=0)
    disturb = models.FloatField(default=0)
    module0 = models.FloatField(default=0)
    module1 = models.FloatField(default=0)
    module2 = models.FloatField(default=0)
    module3 = models.FloatField(default=0)
    module4 = models.FloatField(default=0)
    module5 = models.FloatField(default=0)
    module6 = models.FloatField(default=0)
    module7 = models.FloatField(default=0)
    module8 = models.FloatField(default=0)
    module9 = models.FloatField(default=0)
    module10 = models.FloatField(default=0)
    module11 = models.FloatField(default=0)
    module12 = models.FloatField(default=0)
    module13 = models.FloatField(default=0)
    module14 = models.FloatField(default=0)
    module15 = models.FloatField(default=0)
    module16 = models.FloatField(default=0)
    module17 = models.FloatField(default=0)
    module18 = models.FloatField(default=0)


class CaesarData(models.Model):
    caesarid = models.CharField(max_length=30, null=True)
    cardnum = models.CharField(max_length=50, null=True)
    dmxind01 = models.CharField(max_length=20, null=True)
    dmx10bytestring01 = models.CharField(max_length=20, null=True)
    dmx2bytestring02 = models.CharField(max_length=20, null=True)
    rqotrantimealt = models.CharField(max_length=50, null=True)
    tcaclientamt = models.CharField(max_length=50, null=True)
    rua20bytestring001 = models.CharField(max_length=50, null=True)
    ruaind004 = models.CharField(max_length=20, null=True)
    dmxind03 = models.CharField(max_length=20, null=True)
    sign = models.CharField(max_length=20, null=True)
